### ISSUE TITLE
Explicitly set variables

### ISSUE THREAD

**Issue by keithcml** [bugsnag/bugsnag-dsym-upload#45]
How can I set the release stage via this plugin without setting values in Info.plist.

It's because my info.plist not saving the bugsnag key-value as defaults hierarchy.
I have passed API key into the lane but finding way to pass release stage as well.

**Comment by mattdyoung** [comment]
Hi @keithcml 

You don't need to set the release stage when uploading dSYMs. The dSYMs are applied to stacktraces within your received error reports by matching on the dSYM UUID, so the uploaded dSYM doesn't need to know which release stage the error relates to.

Can you clarify what the issue is you're trying to solve?
